/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "GiftCoin",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GiftCoin__factory>;
    getContractFactory(
      name: "RockPaperScissors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RockPaperScissors__factory>;
    getContractFactory(
      name: "RomanNumerals",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RomanNumerals__factory>;
    getContractFactory(
      name: "TicTacToeChecker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TicTacToeChecker__factory>;

    getContractAt(
      name: "GiftCoin",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.GiftCoin>;
    getContractAt(
      name: "RockPaperScissors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RockPaperScissors>;
    getContractAt(
      name: "RomanNumerals",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RomanNumerals>;
    getContractAt(
      name: "TicTacToeChecker",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TicTacToeChecker>;

    deployContract(
      name: "GiftCoin",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GiftCoin>;
    deployContract(
      name: "RockPaperScissors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RockPaperScissors>;
    deployContract(
      name: "RomanNumerals",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RomanNumerals>;
    deployContract(
      name: "TicTacToeChecker",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TicTacToeChecker>;

    deployContract(
      name: "GiftCoin",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GiftCoin>;
    deployContract(
      name: "RockPaperScissors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RockPaperScissors>;
    deployContract(
      name: "RomanNumerals",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RomanNumerals>;
    deployContract(
      name: "TicTacToeChecker",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TicTacToeChecker>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
