/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RomanNumerals } from "./RomanNumerals";
export * as factories from "./factories";
export { RomanNumerals__factory } from "./factories/RomanNumerals__factory";
